version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./support-api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./sslcert:/sslcert
    links:
      - php
    networks:
      - supportapi

  php:
    build:
      context: ./support-api
      dockerfile: Dockerfile
    image: blaudio/supporto-ift-api
    volumes:
      - ./support-api:/var/www/html
    depends_on:
      - redis
    networks:
      - supportapi

  redis:
    image: redis:7.2.1-bookworm
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - supportapi

networks:
  supportapi:
    driver: bridge
