version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/spreetzitt/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/spreetzitt/sslcert:/etc/nginx/ssl:ro
      - static_files:/var/www/html/public:ro
    networks:
      - app-network
    deploy:
      replicas: 1 # Ridotto a 1 per risparmiare memoria
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          memory: 128M # Ridotto
          cpus: "0.1"
        reservations:
          memory: 64M
          cpus: "0.05"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/spreetzitt-backend:${VERSION:-latest}
    volumes:
      - /opt/spreetzitt/php/supervisord.prod.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - static_files:/var/www/html/public
      - storage_data:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_KEY=${MEILISEARCH_KEY}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - LOG_CHANNEL=stderr
      - SESSION_DRIVER=redis
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      # Ottimizzazioni PHP per memoria limitata
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=60
      - OPCACHE_MEMORY_CONSUMPTION=64
    networks:
      - app-network
    deploy:
      replicas: 1 # Una sola replica per ora
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 60s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 768M # Ridotto ma ragionevole per Laravel
          cpus: "1.2" # Può utilizzare più CPU quando necessario
        reservations:
          memory: 384M
          cpus: "0.4"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "php", "artisan", "inspire"]
      interval: 45s # Meno frequente per risparmiare risorse
      timeout: 20s
      retries: 2
      start_period: 120s

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/spreetzitt-frontend:${VERSION:-latest}
    networks:
      - app-network
    deploy:
      replicas: 1 # Una sola replica
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          memory: 256M # Ridotto significativamente
          cpus: "0.3"
        reservations:
          memory: 128M
          cpus: "0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 45s
      timeout: 15s
      retries: 2
      start_period: 60s

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --appendfsync everysec --maxmemory 128mb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10
    volumes:
      - redis_data:/data
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          memory: 160M # Ridotto
          cpus: "0.2"
        reservations:
          memory: 96M
          cpus: "0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 45s
      timeout: 10s
      retries: 2
      start_period: 30s

  meilisearch:
    image: getmeili/meilisearch:v1.5
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
      - MEILI_HTTP_ADDR=0.0.0.0:7700
      - MEILI_ENV=production
      - MEILI_LOG_LEVEL=WARN # Meno verbose
      - MEILI_MAX_INDEXING_MEMORY=128Mb # Ridotto
      - MEILI_MAX_INDEXING_THREADS=1 # Single thread
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          memory: 256M # Molto ridotto
          cpus: "0.3"
        reservations:
          memory: 128M
          cpus: "0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:7700/health",
        ]
      interval: 60s # Meno frequente
      timeout: 15s
      retries: 2
      start_period: 60s

networks:
  app-network:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"

volumes:
  meilisearch_data:
    driver: local
  redis_data:
    driver: local
  static_files:
    driver: local
  storage_data:
    driver: local

# Configurazioni per ottimizzare le performance su istanza piccola
configs:
  nginx_config:
    file: /opt/spreetzitt/nginx/default.prod.conf
  supervisord_config:
    file: /opt/spreetzitt/php/supervisord.prod.conf

secrets:
  app_key:
    external: true
  redis_password:
    external: true
  meilisearch_key:
    external: true
