apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spreetzitt-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 60
      containers:
        - image: gcr.io/PROJECT_ID/spreetzitt-frontend:latest
          ports:
            - containerPort: 8080
          # Health check configuration per Cloud Run
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /startup
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
      serviceAccountName: PROJECT_ID-compute@developer.gserviceaccount.com
