# 🚀 Google Cloud Run - Service Configuration Template
# Configurazione declarativa per i servizi Cloud Run

# Backend Service Configuration
backend:
  apiVersion: serving.knative.dev/v1
  kind: Service
  metadata:
    name: spreetzitt-backend
    annotations:
      run.googleapis.com/ingress: all
      run.googleapis.com/execution-environment: gen2
  spec:
    template:
      metadata:
        annotations:
          autoscaling.knative.dev/minScale: "0"
          autoscaling.knative.dev/maxScale: "10"
          run.googleapis.com/cpu-throttling: "false"
      spec:
        containerConcurrency: 80
        timeoutSeconds: 300
        containers:
          - image: gcr.io/PROJECT_ID/spreetzitt-backend:latest
            ports:
              - containerPort: 8080
            env:
              - name: APP_ENV
                value: production
              - name: SCOUT_DRIVER
                value: database
            resources:
              limits:
                cpu: 1000m
                memory: 1Gi
        serviceAccountName: PROJECT_ID-compute@developer.gserviceaccount.com

---
# Frontend Service Configuration
frontend:
  apiVersion: serving.knative.dev/v1
  kind: Service
  metadata:
    name: spreetzitt-frontend
    annotations:
      run.googleapis.com/ingress: all
      run.googleapis.com/execution-environment: gen2
  spec:
    template:
      metadata:
        annotations:
          autoscaling.knative.dev/minScale: "0"
          autoscaling.knative.dev/maxScale: "5"
      spec:
        containerConcurrency: 1000
        timeoutSeconds: 60
        containers:
          - image: gcr.io/PROJECT_ID/spreetzitt-frontend:latest
            ports:
              - containerPort: 8080
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
        serviceAccountName: PROJECT_ID-compute@developer.gserviceaccount.com
